/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vinsen_application_VoiceHelper */

#ifndef _Included_com_vinsen_application_VoiceHelper
#define _Included_com_vinsen_application_VoiceHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vinsen_application_VoiceHelper
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_vinsen_application_VoiceHelper_play
  (JNIEnv *, jclass,jstring);

#ifdef __cplusplus
}
#endif
#endif
